import java.nio.charset.StandardCharsets
import java.nio.file.Files
import java.nio.file.Path
import java.util.Locale

// Run Gradle with JDK 21:
// ./gradlew -I tools/GenerateUnicodeNames.init.gradle.kts generateUnicodeNames
private val chunkSize = 30_000
private val defaultOutput = "src/commonMain/kotlin/internal/UnicodeNames.kt"

private data class Entry(val name: String, val codePoint: Int)
private data class GeneratedRange(val prefix: String, val start: Int, val end: Int)

private fun generateUnicodeNames(outputPath: Path) {
    check(Runtime.version().feature() == 21) {
        "Run Gradle with JDK 21 so names match Minecraft's Unicode 15.0 data"
    }

    val entries = mutableListOf<Entry>()
    val generatedRanges = mutableListOf<GeneratedRange>()

    for (codePoint in Character.MIN_CODE_POINT..Character.MAX_CODE_POINT) {
        val name = Character.getName(codePoint) ?: continue
        val hexadecimal = codePoint.toString(16).uppercase(Locale.ROOT)
        val generatedSuffix = when {
            name.endsWith(" $hexadecimal") -> " $hexadecimal"
            name.endsWith("-$hexadecimal") -> "-$hexadecimal"
            else -> null
        }

        if (generatedSuffix != null) {
            appendRange(
                ranges = generatedRanges,
                prefix = name.substring(0, name.length - hexadecimal.length),
                codePoint = codePoint,
            )
        } else {
            entries += Entry(name, codePoint)
        }
    }

    val entryChunks = entries
        .map { (name, codePoint) -> "$name\t${codePoint.toString(16)}" }
        .chunk()
    val rangeChunks = generatedRanges
        .map { (prefix, start, end) -> "$prefix\t${start.toString(16)}\t${end.toString(16)}" }
        .chunk()

    val output = StringBuilder()
    output.append(
        """package net.benwoodworth.knbt.internal

// Generated by tools/GenerateUnicodeNames.init.gradle.kts with JDK 21 (Unicode 15.0).
// Do not edit this file manually.

internal fun unicodeCodePointByName(name: String): Int? {
    val normalizedName = name.trim().uppercase()
    unicodeNames[normalizedName]?.let { return it }

    val hexadecimalStart = normalizedName.indexOfLast { it !in '0'..'9' && it !in 'A'..'F' } + 1
    if (hexadecimalStart <= 0 || hexadecimalStart == normalizedName.length) return null
    val codePoint = normalizedName.substring(hexadecimalStart).toIntOrNull(16) ?: return null
    val prefix = normalizedName.substring(0, hexadecimalStart)
    return codePoint.takeIf { candidate ->
        generatedUnicodeNameRanges[prefix]?.any { candidate in it } == true
    }
}

private val unicodeNames: Map<String, Int> by lazy {
    val result = mutableMapOf<String, Int>()
    unicodeNameData.forEach { chunk ->
        chunk.lineSequence().forEach { line ->
            val separator = line.lastIndexOf('\t')
            result[line.substring(0, separator)] = line.substring(separator + 1).toInt(16)
        }
    }
    result
}

private val generatedUnicodeNameRanges: Map<String, List<IntRange>> by lazy {
    val result = mutableMapOf<String, MutableList<IntRange>>()
    generatedUnicodeNameRangeData.forEach { chunk ->
        chunk.lineSequence().forEach { line ->
            val fields = line.split('\t')
            result.getOrPut(fields[0]) { mutableListOf() }
                .add(fields[1].toInt(16)..fields[2].toInt(16))
        }
    }
    result
}

""",
    )
    output.appendChunks("unicodeNameData", entryChunks)
    output.appendChunks("generatedUnicodeNameRangeData", rangeChunks)
    output.setLength(output.length - 1)

    Files.createDirectories(outputPath.parent)
    Files.writeString(outputPath, output, StandardCharsets.UTF_8)
}

private fun appendRange(ranges: MutableList<GeneratedRange>, prefix: String, codePoint: Int) {
    val previous = ranges.lastOrNull()
    if (previous?.prefix == prefix && previous.end + 1 == codePoint) {
        ranges[ranges.lastIndex] = GeneratedRange(prefix, previous.start, codePoint)
    } else {
        ranges += GeneratedRange(prefix, codePoint, codePoint)
    }
}

private fun List<String>.chunk(): List<String> = buildList {
    val chunk = StringBuilder()
    for (line in this@chunk) {
        if (chunk.isNotEmpty() && chunk.length + line.length + 1 > chunkSize) {
            add(chunk.toString())
            chunk.clear()
        }
        if (chunk.isNotEmpty()) chunk.append('\n')
        chunk.append(line)
    }
    if (chunk.isNotEmpty()) add(chunk.toString())
}

private fun StringBuilder.appendChunks(name: String, chunks: List<String>) {
    append("private val ").append(name).append(" = arrayOf(\n")
    chunks.indices.forEach { index ->
        append("    ").append(name).append(index).append(",\n")
    }
    append(")\n\n")
    chunks.forEachIndexed { index, chunk ->
        append("private const val ").append(name).append(index).append(" = \"\"\"")
            .append(chunk).append("\"\"\"\n\n")
    }
}

gradle.projectsLoaded {
    rootProject.tasks.register("generateUnicodeNames") {
        group = "generation"
        description = "Generates the Unicode 15 name index used by modern SNBT named escapes."

        doLast {
            val output = rootProject.findProperty("unicodeNamesOutput")?.toString() ?: defaultOutput
            generateUnicodeNames(rootProject.file(output).toPath())
        }
    }
}
